import '../globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {notFound} from "next/navigation";
import {NextIntlClientProvider, useLocale} from "next-intl";
import {ReactNode} from "react";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Simplifyr',
    description: 'Generated by create next app',
}

export function generateStaticParams() {
    return [{locale: 'en'}, {locale: 'es'}];
}

export default async function LocaleLayout({children, params,}: {
    children: ReactNode;
    params: { locale: string };
}) {
    const locale = useLocale();

    // Show a 404 error if the user requests an unknown locale
    if (params.locale !== locale) {
        notFound();
    }

    let messages;
    try {
        messages = (await import(`../../messages/${locale}.json`)).default;
    } catch (error) {
        notFound();
    }


    return (
        <html lang={locale}>
            <body className={inter.className}>
                <NextIntlClientProvider locale={locale} messages={messages}>
                  {children}
                </NextIntlClientProvider>
            </body>
        </html>
    )
}
